version: "3.8"

services:
  app:
    user: ${PUID}:${PGID}
    build:
      context: ./app
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - VERSION=${PHP_VERSION}
        - NODE_VERSION=${NODE_VERSION}
        - XDEBUG_VERSION=${XDEBUG_VERSION}
    image: ${PREFIX}-app
    container_name: ${PREFIX}-app
    working_dir: /var/www
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ../:/var/www:delegated
      - ./app/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini:delegated
      - ./app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:delegated
    expose:
      - "9000"

  nginx:
    build:
      context: ./nginx
      args:
        - PREFIX=${PREFIX}
        - PHP_UPSTREAM_CONTAINER=${PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${PHP_UPSTREAM_PORT}
    image: ${PREFIX}-nginx
    container_name: ${PREFIX}-nginx
    working_dir: /var/www
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ../:/var/www:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
    depends_on:
      - app

  postgres:
    image: ${PREFIX}-postgres
    container_name: ${PREFIX}-postgres
    build:
      context: ./postgres
      args:
        - VERSION=${POSTGRES_VERSION}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    depends_on:
      - app

volumes:
  db_data: